name: Build Packages

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        series: [bionic, focal, jammy]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts build-essential lintian dput-ng python3-dev \
          debhelper cmake pkg-config libz-dev libmbedtls-dev libssh2-1-dev \
          libhttp-parser-dev libkrb5-dev python-is-python3
    
    - name: Import PGP key
      env:
        PGP_KEY: ${{ secrets.PGP_KEY }}
        GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      run: |
        if [ -z "${PGP_KEY:-}" ]; then
          echo "No PGP_KEY provided; skipping GPG import."
          exit 0
        fi
        # Create GPG directories and configure for non-interactive mode
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        
        # Configure GPG and gpg-agent for CI
        cat > ~/.gnupg/gpg.conf << EOF
        use-agent
        pinentry-mode loopback
        allow-freeform-uid
        EOF
        
        cat > ~/.gnupg/gpg-agent.conf << EOF
        allow-loopback-pinentry
        EOF
        
        # Restart gpg-agent with new config
        gpgconf --kill gpg-agent
        gpgconf --launch gpg-agent
        
        # Import the key with batch mode
        echo "$PGP_KEY" | gpg --batch --import
        
        # Trust the key (extract fingerprint, not key ID)
        FINGERPRINT=$(gpg --list-keys --with-colons vladtemian@gmail.com | awk -F: '/^fpr:/ { print $10; exit }')
        echo "$FINGERPRINT:6:" | gpg --import-ownertrust
    
    - name: Build packages
      env:
        DEBEMAIL: "vladtemian@gmail.com"
        DEBFULLNAME: "Vlad Temian"
        SERIES: ${{ matrix.series }}
        GITHUB_ACTIONS: true
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GNUPGHOME: /home/runner/.gnupg
        GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      run: |
        make clean
        make build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ matrix.series }}
        path: build/
    
    - name: Deploy to PPA (master branch)
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      env:
        PGP_KEY: ${{ secrets.PGP_KEY }}
      run: |
        if [ -z "${PGP_KEY:-}" ]; then
          echo "No PGP_KEY provided; skipping PPA upload."
          exit 0
        fi
        cd build && dput ppa:vladtemian/gitfs *.changes
